spring:
  datasource:
    url: jdbc:tc:postgresql:15:///testdb
    driver-class-name: org.testcontainers.jdbc.ContainerDatabaseDriver

  jpa:
    hibernate:
      ddl-auto: validate

  kafka:
    bootstrap-servers: ${spring.embedded.kafka.brokers}

  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://localhost:8080/realms/food-delivery

logging:
  level:
    com.fooddelivery.restaurant: DEBUG
